Some changes to have VN work together with Interactive Narrator. I still get the following error message though. Perhaps you know how to fix it. Probably has to do with the extra parameter i added to main().
Initializing Natural Language Processor . . .
Traceback (most recent call last):
  File "run.py", line 310, in <module>
    program()
  File "run.py", line 299, in program
    args.per_role, args.threshold, args.base_weight, weights, args.visualize)
  File "run.py", line 37, in main
    set = Reader.parse(filename)
  File "/home/gjslob/Documents/environments/inarrator/VisualNarrator/app/io.py", line 12, in parse
    with open_file:
ValueError: I/O operation on closed file.